/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
export * as gameSol from './Game.sol';
export { BlackBox__factory } from './BlackBox__factory';
=======
export { BlackBox__factory } from "./BlackBox__factory";
export { Game__factory } from "./Game__factory";
export { Greeter__factory } from "./Greeter__factory";
>>>>>>> 6d267f1 (add hardhat tests)
