/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
import type * as contractsUpgradeable from './contracts-upgradeable';
export type { contractsUpgradeable };
=======
import type * as contracts from "./contracts";
export type { contracts };
>>>>>>> 6d267f1 (add hardhat tests)
