/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameSol from './Game.sol';
export type { gameSol };
export type { BlackBox } from './BlackBox';
