/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
<<<<<<< HEAD
import type * as gameSol from './Game.sol';
export type { gameSol };
export type { BlackBox } from './BlackBox';
=======
export type { BlackBox } from "./BlackBox";
export type { Game } from "./Game";
export type { Greeter } from "./Greeter";
>>>>>>> 6d267f1 (add hardhat tests)
